# Generated by Django 4.2 on 2024-05-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adltest',
        ),
    ]
