# Generated by Django 4.2 on 2024-06-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_rename_user_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
