# Generated by Django 4.2 on 2024-06-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('arrendatario', 'Arrendatario'), ('arrendador', 'Arrendador')]),
        ),
    ]
