# Generated by Django 4.2 on 2024-06-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fecha_recepcion',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-06 12:00:00'),
            preserve_default=False,
        ),
    ]
