# Generated by Django 4.2 on 2024-06-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0006_contact_fecha_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
