# Generated by Django 4.2 on 2024-05-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(related_name='Profesores', to='bootcamps.profesor'),
        ),
    ]
