# Generated by Django 4.2 on 2024-05-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0002_curso_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='Estudiantes', to='bootcamps.estudiante'),
        ),
    ]
