# Generated by Django 4.2 on 2024-05-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0003_curso_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estudiantes',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesores',
        ),
    ]
