# Generated by Django 4.2 on 2024-05-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_promocion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocion',
        ),
    ]
