# Generated by Django 4.2 on 2024-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_promocion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='flan_uuid',
            new_name='promocion_uuid',
        ),
    ]
